//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckItem) DeepCopyInto(out *CheckItem) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckItem.
func (in *CheckItem) DeepCopy() *CheckItem {
	if in == nil {
		return nil
	}
	out := new(CheckItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CheckResult) DeepCopyInto(out *CheckResult) {
	*out = *in
	if in.Evidence != nil {
		in, out := &in.Evidence, &out.Evidence
		*out = new(Evidence)
		(*in).DeepCopyInto(*out)
	}
	if in.FailedSince != nil {
		in, out := &in.FailedSince, &out.FailedSince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CheckResult.
func (in *CheckResult) DeepCopy() *CheckResult {
	if in == nil {
		return nil
	}
	out := new(CheckResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChecklistPolicy) DeepCopyInto(out *ChecklistPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChecklistPolicy.
func (in *ChecklistPolicy) DeepCopy() *ChecklistPolicy {
	if in == nil {
		return nil
	}
	out := new(ChecklistPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChecklistPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChecklistPolicyList) DeepCopyInto(out *ChecklistPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChecklistPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChecklistPolicyList.
func (in *ChecklistPolicyList) DeepCopy() *ChecklistPolicyList {
	if in == nil {
		return nil
	}
	out := new(ChecklistPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChecklistPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChecklistPolicySpec) DeepCopyInto(out *ChecklistPolicySpec) {
	*out = *in
	out.Schedule = in.Schedule
	out.LLM = in.LLM
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]CheckItem, len(*in))
		copy(*out, *in)
	}
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Notification != nil {
		in, out := &in.Notification, &out.Notification
		*out = new(NotificationConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.EscalationThreshold != nil {
		in, out := &in.EscalationThreshold, &out.EscalationThreshold
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChecklistPolicySpec.
func (in *ChecklistPolicySpec) DeepCopy() *ChecklistPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ChecklistPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChecklistPolicyStatus) DeepCopyInto(out *ChecklistPolicyStatus) {
	*out = *in
	if in.LastFullScanTime != nil {
		in, out := &in.LastFullScanTime, &out.LastFullScanTime
		*out = (*in).DeepCopy()
	}
	if in.LastRescanTime != nil {
		in, out := &in.LastRescanTime, &out.LastRescanTime
		*out = (*in).DeepCopy()
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(ScanSummary)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChecklistPolicyStatus.
func (in *ChecklistPolicyStatus) DeepCopy() *ChecklistPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ChecklistPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChecklistResult) DeepCopyInto(out *ChecklistResult) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChecklistResult.
func (in *ChecklistResult) DeepCopy() *ChecklistResult {
	if in == nil {
		return nil
	}
	out := new(ChecklistResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChecklistResult) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChecklistResultList) DeepCopyInto(out *ChecklistResultList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ChecklistResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChecklistResultList.
func (in *ChecklistResultList) DeepCopy() *ChecklistResultList {
	if in == nil {
		return nil
	}
	out := new(ChecklistResultList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ChecklistResultList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChecklistResultSpec) DeepCopyInto(out *ChecklistResultSpec) {
	*out = *in
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	if in.CompletedAt != nil {
		in, out := &in.CompletedAt, &out.CompletedAt
		*out = (*in).DeepCopy()
	}
	if in.Checks != nil {
		in, out := &in.Checks, &out.Checks
		*out = make([]CheckResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Summary != nil {
		in, out := &in.Summary, &out.Summary
		*out = new(ScanSummary)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChecklistResultSpec.
func (in *ChecklistResultSpec) DeepCopy() *ChecklistResultSpec {
	if in == nil {
		return nil
	}
	out := new(ChecklistResultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChecklistResultStatus) DeepCopyInto(out *ChecklistResultStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChecklistResultStatus.
func (in *ChecklistResultStatus) DeepCopy() *ChecklistResultStatus {
	if in == nil {
		return nil
	}
	out := new(ChecklistResultStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Evidence) DeepCopyInto(out *Evidence) {
	*out = *in
	if in.ToolCalls != nil {
		in, out := &in.ToolCalls, &out.ToolCalls
		*out = make([]ToolCallRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Evidence.
func (in *Evidence) DeepCopy() *Evidence {
	if in == nil {
		return nil
	}
	out := new(Evidence)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubNotification) DeepCopyInto(out *GitHubNotification) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubNotification.
func (in *GitHubNotification) DeepCopy() *GitHubNotification {
	if in == nil {
		return nil
	}
	out := new(GitHubNotification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JiraNotification) DeepCopyInto(out *JiraNotification) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JiraNotification.
func (in *JiraNotification) DeepCopy() *JiraNotification {
	if in == nil {
		return nil
	}
	out := new(JiraNotification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMConfig) DeepCopyInto(out *LLMConfig) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMConfig.
func (in *LLMConfig) DeepCopy() *LLMConfig {
	if in == nil {
		return nil
	}
	out := new(LLMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationConfig) DeepCopyInto(out *NotificationConfig) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackNotification)
		**out = **in
	}
	if in.GitHub != nil {
		in, out := &in.GitHub, &out.GitHub
		*out = new(GitHubNotification)
		(*in).DeepCopyInto(*out)
	}
	if in.Jira != nil {
		in, out := &in.Jira, &out.Jira
		*out = new(JiraNotification)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationConfig.
func (in *NotificationConfig) DeepCopy() *NotificationConfig {
	if in == nil {
		return nil
	}
	out := new(NotificationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScanSummary) DeepCopyInto(out *ScanSummary) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScanSummary.
func (in *ScanSummary) DeepCopy() *ScanSummary {
	if in == nil {
		return nil
	}
	out := new(ScanSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleConfig) DeepCopyInto(out *ScheduleConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleConfig.
func (in *ScheduleConfig) DeepCopy() *ScheduleConfig {
	if in == nil {
		return nil
	}
	out := new(ScheduleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackNotification) DeepCopyInto(out *SlackNotification) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackNotification.
func (in *SlackNotification) DeepCopy() *SlackNotification {
	if in == nil {
		return nil
	}
	out := new(SlackNotification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ToolCallRecord) DeepCopyInto(out *ToolCallRecord) {
	*out = *in
	if in.Input != nil {
		in, out := &in.Input, &out.Input
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ToolCallRecord.
func (in *ToolCallRecord) DeepCopy() *ToolCallRecord {
	if in == nil {
		return nil
	}
	out := new(ToolCallRecord)
	in.DeepCopyInto(out)
	return out
}
