{{- if and .Values.ui.enabled .Values.ui.auth.enabled (not .Values.ui.auth.existingSecret) }}
{{- $secretName := printf "%s-auth" (include "dtm.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Values.namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dtm.uiLabels" . | nindent 4 }}
type: Opaque
data:
  {{- if $existingSecret }}
  username: {{ index $existingSecret.data "username" }}
  password: {{ index $existingSecret.data "password" }}
  {{- else }}
  username: {{ .Values.ui.auth.username | b64enc | quote }}
  password: {{ (default (randAlphaNum 22) .Values.ui.auth.password) | b64enc | quote }}
  {{- end }}
{{- end }}
