apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dtm.fullname" . }}-operator
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "dtm.operatorLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: dtm-operator
  template:
    metadata:
      labels:
        {{- include "dtm.operatorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.operator.serviceAccount.name }}
      containers:
        - name: operator
          image: "{{ .Values.operator.image.repository }}:{{ .Values.operator.image.tag }}"
          imagePullPolicy: {{ .Values.operator.image.pullPolicy }}
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
          ports:
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
